In [1]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv('datas/winequality-white.csv', sep=';')

In [14]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [15]:
df.shape

(4898, 12)

In [26]:
df['quality'].value_counts()

6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: quality, dtype: int64

In [35]:
df_train = df.iloc[0:4890, :]

In [32]:
df_test = df.iloc[4890:, :]

In [36]:
df_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.80,6
1,6.3,0.300,0.34,1.60,0.049,14.0,132.0,0.99400,3.30,0.49,9.50,6
2,8.1,0.280,0.40,6.90,0.050,30.0,97.0,0.99510,3.26,0.44,10.10,6
3,7.2,0.230,0.32,8.50,0.058,47.0,186.0,0.99560,3.19,0.40,9.90,6
4,7.2,0.230,0.32,8.50,0.058,47.0,186.0,0.99560,3.19,0.40,9.90,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4885,6.6,0.340,0.40,8.10,0.046,68.0,170.0,0.99494,3.15,0.50,9.55,6
4886,6.2,0.210,0.28,5.70,0.028,45.0,121.0,0.99168,3.21,1.08,12.15,7
4887,6.2,0.410,0.22,1.90,0.023,5.0,56.0,0.98928,3.04,0.79,13.00,7
4888,6.8,0.220,0.36,1.20,0.052,38.0,127.0,0.99330,3.04,0.54,9.20,5
4889,4.9,0.235,0.27,11.75,0.030,34.0,118.0,0.99540,3.07,0.50,9.40,6

In [37]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [39]:
features = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar','chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density','pH', 'sulphates', 'alcohol']

In [41]:
X = df_train[features].copy()

In [42]:
y = df_train['quality'].copy()

In [43]:
X.shape

(4890, 11)

In [45]:
y.shape

(4890,)

In [47]:
def sigmoid(X, theta):
    z = X*theta
    return 1/(1+np.exp(-z))
theta = np.zeros(X.shape[1])
def cost(X,y,theta, alpha):
    h = sigmoid(X, theta)
    m = X.shape[0]
    cost_1 = -y*np.log(h)
    cost_2 = -(1-y)*np.log(1-h)
    print(cost_1)
    cost_total = (1/m)*(cost_1+cost_2).sum()
    return cost_total

In [48]:
theta = np.zeros(X.shape[1])

In [53]:
def cost(X,y,theta, alpha):
    h = sigmoid(X, theta)
    m = X.shape[0]
    cost_1 = -y*np.log(h)
    cost_2 = -(1-y)*np.log(1-h)
    print(cost_1)
    cost_total = (1/m)*(cost_1+cost_2).sum()
    return cost_total

In [51]:
alpha=0.01

0       6
1       6
2       6
3       6
4       6
       ..
4885    6
4886    7
4887    7
4888    5
4889    6
Name: quality, Length: 4890, dtype: int64

In [54]:
cost(X,y,theta, alpha)

       0   1   2   3   4   5   6   7   8   9  ...  chlorides  citric acid  \
0    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN
1    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN
2    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN
3    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN
4    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...        ...          ...
4885 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN
4886 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN
4887 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN
4888 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN
4889 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...        NaN          NaN

      density  fixed acidity  free sulfur dioxide  pH  residual sugar  \
0         NaN            NaN                  NaN NaN             NaN
1         NaN            NaN                  NaN NaN             NaN
2         NaN            NaN                  NaN NaN             NaN
3         NaN            NaN                  NaN NaN             NaN
4         NaN            NaN                  NaN NaN             NaN
...       ...            ...                  ...  ..             ...
4885      NaN            NaN                  NaN NaN             NaN
4886      NaN            NaN                  NaN NaN             NaN
4887      NaN            NaN                  NaN NaN             NaN
4888      NaN            NaN                  NaN NaN             NaN
4889      NaN            NaN                  NaN NaN             NaN

      sulphates  total sulfur dioxide  volatile acidity
0           NaN                   NaN               NaN
1           NaN                   NaN               NaN
2           NaN                   NaN               NaN
3           NaN                   NaN               NaN
4           NaN                   NaN               NaN
...         ...                   ...               ...
4885        NaN                   NaN               NaN
4886        NaN                   NaN               NaN
4887        NaN                   NaN               NaN
4888        NaN                   NaN               NaN
4889        NaN                   NaN               NaN

[4890 rows x 4901 columns]

0                       0.0
1                       0.0
2                       0.0
3                       0.0
4                       0.0
                       ...
pH                      0.0
residual sugar          0.0
sulphates               0.0
total sulfur dioxide    0.0
volatile acidity        0.0
Length: 4901, dtype: float64

In [56]:
df = pd.read_csv('datas/diabetes2.csv')

In [59]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [61]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [62]:
features = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

In [66]:
X = pd.concat([pd.Series(np.ones(df.shape[0])), df[features].copy()], axis=1)

In [67]:
X

,0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,1.0,6,148,72,35,0,33.6,0.627,50
1,1.0,1,85,66,29,0,26.6,0.351,31
2,1.0,8,183,64,0,0,23.3,0.672,32
3,1.0,1,89,66,23,94,28.1,0.167,21
4,1.0,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...,...
763,1.0,10,101,76,48,180,32.9,0.171,63
764,1.0,2,122,70,27,0,36.8,0.340,27
765,1.0,5,121,72,23,112,26.2,0.245,30
766,1.0,1,126,60,0,0,30.1,0.349,47
767,1.0,1,93,70,31,0,30.4,0.315,23

In [69]:
y = df['Outcome'].copy()

In [70]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [118]:
def sigmoid(X, theta):
    z = (X*theta).sum(axis=1)
    return 1/(1+np.exp(-z))

theta = np.zeros(X.shape[1])

def cost(X,y,theta, alpha):
    h = sigmoid(X, theta)
    m = X.shape[0]
    cost_1 = -y*np.log(h)
    cost_2 = -(1-y)*np.log(1-h)
#     print(cost_1)
    cost_total = (1/m)*(cost_1+cost_2).sum()
    return cost_total

In [124]:
alpha = 0.01
cost(X, y, theta, alpha)

0.6931471805599452

In [114]:
h = sigmoid(X, theta)

In [117]:
-y*np.log(h)

0      0.693147
1     -0.000000
2      0.693147
3     -0.000000
4      0.693147
         ...
763   -0.000000
764   -0.000000
765   -0.000000
766    0.693147
767   -0.000000
Length: 768, dtype: float64

In [118]:
def sigmoid(X, theta):
    z = (X*theta).sum(axis=1)
    return 1/(1+np.exp(-z))

theta = np.zeros(X.shape[1])

def cost(X,y,theta, alpha):
    h = sigmoid(X, theta)
    m = X.shape[0]
    cost_1 = -y*np.log(h)
    cost_2 = -(1-y)*np.log(1-h)
#     print(cost_1)
    cost_total = (1/m)*(cost_1+cost_2).sum()
    return cost_total

In [136]:
def gradient_descent(X, y, theta, loop):
    cost_matrix = []
    m = X.shape[0]
    for i in range(loop):
        h = sigmoid(X, theta)
        cost_total = cost(X, y, theta, alpha)
        print(cost_total)
        cost_matrix.append(cost_total)
        for j in range(theta.shape[0]):
            theta[j] = theta[j]-((1/m)*((h-y)*X.iloc[:,j]).sum())
    return theta, cost_matrix

In [137]:
gradient_descent(X, y, theta,100)

/home/bishal/anaconda3/lib/python3.7/site-packages/pandas/core/series.py:679: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
/home/bishal/anaconda3/lib/python3.7/site-packages/pandas/core/series.py:679: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf

(array([-10.50430579,  56.64287426,  21.02003354, -89.23845987,
         -3.9888192 , -19.58109391,   6.33916194,   2.15146553,
         13.24321506]),
 [inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf,
  inf])

In [ ]:
import matplot.pyplot as plt
plt.plot(100, cost_matrix)