In [1]:
ls

'cleaner and profanity for csv.ipynb'   mongodb.ipynb
 datas/                                'randomize columns.ipynb'
 hrank.ipynb

In [4]:
ls datas/

class11datacollection.csv   cleaned_class11datacollection.csv
Class11DataCollection.xlsx

In [5]:
import pandas as pd

file_name = 'datas/Class11DataCollection.xlsx'
df = pd.read_excel(file_name, sheet_name=None)
df['Biology']

,S.N.,Question,Option A,Option B,Option C,Option D,Correct Option
0,1,They are the remains or impressions of living ...,Tissues,Fossils,Calcium,Statutes,B
1,2,It is the study of fossils and their relations...,Embryology,Taxonomy,Physiology,None of these,D
2,3,Man has been able to produce food in greater q...,Mathematics,Space science,Physics,Biology,D
3,4,Taxonomy is the study of:,Functions of different parts of organisms,Naming and classification of organisms,Hereditary characters,Structure and functions of cells,B
4,5,Anatomy deals with the study of:,Relationship between organisms and their envir...,Development of an organism from a fertilized e...,Structure and function of molecular components...,Internal organs of organisms,D
...,...,...,...,...,...,...,...
194,195,At the end of the electron transport chain dur...,Nad,Fad,Oxygen,Hydrogen,C
195,196,During growth fibers elongate greatly:,At right angle to the long axis,Parallel to the long axis,Obliquely to the long axis,In all directions,B
196,197,Which of these is the naturally occurring auxins?,Indole acetic acid,"2, 4-d",Abscisic acid,Butyric acid,A
197,198,The application of auxin in small amount:,Stimulate the growth of leaves,Retard the growth of leaves,Suppress the growth of leaves,Does not affect the growth of laves,D
198,199,Which of these increases the growth rate of is...,Auxins,Cytokinins,Gibberellins,None of these,B

In [7]:
df.keys()

dict_keys(['Physics', 'Chemistry', 'Biology', 'Account', 'Business Studies', 'Finance', 'Sociology', 'Math', 'Economics', 'English'])

In [8]:
df['Finance']

,S.N.,Question,Option A,Option B,Option C,Option D,Correct Option
0,1,The financial market where debt and stocks are...,Short term markets,Capital markets,Counter markets,Long term markets,B
1,2,The type of market in which securities with le...,Money market,Capital market,Transaction market,None,A
2,3,The markets in which new securities are issued...,Primary markets,Secondary market,Gross market,None,A
3,4,Which types of preference shares can be conver...,Redeemable bonds,Convertible bonds,Non- convertible bonds,All,B
4,5,Bonds which are sold at very high discount and...,Discount bonds,Premium bond,Zero coupon bonds,Convertible bond,C
...,...,...,...,...,...,...,...
180,181,Centralized market place where agents can hace...,Secondary market,Central market,Traded market,Agents market,A
181,182,Treasury bonds and notes pay interest rate is ...,Coupon interest monthly,Coupon interest semi annually,Coupon interest annually,None,B
182,183,As compared to treasury bonds trading of munic...,More index inflation,Less index inflation,Less active,More active,C
183,184,Stocks or shares that are sold to investors wi...,Direct transfer,Indirect transfer,Global transfer,None,A
184,185,Bonds that are backed by cash flow from projec...,Finance bonds,Revenue bonds,Financing bonds,Project bonds,B