In [26]:
with open("Wall.txt") as f:
    w = f.readlines()

In [27]:
len(w)

16

In [28]:
data = w[0].split("\t")

In [29]:
len(data)

16489

In [ ]:
w[0]

'19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t12\t0\t0\t0,4086559\t4096\t293,6013\t0,22\t0\t0\t47621\t10\t18\t26\t30\t36\t-293\t-257\t-221\t-183\t-151\t-120\t-72\t-23\t32\t79\t119\t146\t161\t179\t194\t212\t225\t229\t222\t196\t164\t133\t97\t75\t49\t24\t-5\t-43\t-77\t-106\t-129\t-143\t-149\t-149\t-152\t-155\t-150\t-133\t-102\t-71\t-37\t-11\t11\t32\t51\t81\t101\t125\t147\t158\t155\t142\t130\t112\t97\t85\t66\t38\t4\t-36\t-80\t-113\t-133\t-156\t-174\t-194\t-211\t-219\t-219\t-212\t-202\t-180\t-155\t-129\t-100\t-67\t-30\t15\t66\t112\t154\t188\t214\t233\t253\t271\t285\t290\t285\t268\t236\t201\t163\t127\t91\t49\t5\t-53\t-110\t-172\t-215\t-250\t-277\t-298\t-316\t-333\t-342\t-343\t-330\t-307\t-271\t-235\t-195\t-154\t-107\t-56\t2\t66\t124\t175\t220\t260\t289\t319\t339\t359\t366\t364\t344\t314\t281\t236\t194\t153\t109\t58\t-3\t-65\t-131\t-181\t-223\t-263\t-301\t-327\t-348\t-363\t-369\t-358\t-341\t-312\t-283\t-255\t-216\t-173\t-124\t-69\t-7\t52\t105\t153\t188\t217\t249\t278\t299\t318\t322\t309\t289\t266\t233\t204\t176\t141\t100\t54\t1\t-45\t-84\t-117\t-151\t-181\t-202\t-224\t-238\t-248\t-243\t-241\t-220\t-195\t-173\t-152\t-126\t-92\t-59\t-25\t10\t41\t72\t90\t104\t122\t136\t149\t161\t166\t155\t137\t115\t96\t79\t66\t43\t22\t3\t-22\t-51\t-72\t-85\t-96\t-103\t-108\t-113\t-107\t-98\t-88\t-75\t-56\t-38\t-26\t-12\t8\t27\t49\t64\t82\t89\t100\t99\t91\t86\t80\t68\t57\t40\t18\t-8\t-25\t-45\t-65\t-82\t-96\t-113\t-123\t-133\t-144\t-149\t-139\t-130\t-114\t-97\t-81\t-58\t-38\t-8\t21\t52\t83\t108\t126\t150\t167\t185\t200\t204\t198\t195\t180\t157\t131\t107\t79\t49\t16\t-16\t-53\t-84\t-121\t-157\t-184\t-207\t-230\t-251\t-259\t-262\t-254\t-238\t-219\t-199\t-170\t-144\t-115\t-81\t-42\t1\t48\t92\t129\t164\t188\t216\t245\t264\t273\t301\t313\t305\t280\t254\t222\t184\t148\t102\t50\t1\t-51\t-96\t-139\t-175\t-212\t-244\t-272\t-298\t-314\t-318\t-314\t-297\t-273\t-249\t-224\t-192\t-149\t-111\t-67\t-16\t33\t78\t118\t152\t179\t207\t229\t246\t259\t264\t262\t255\t234\t211\t182\t158\t121\t87\t51\t16\t-26\t-57\t-89\t-116\t-144\t-171\t-193\t-210\t-220\t-219\t-208\t-195\t-181\t-166\t-149\t-128\t-106\t-81\t-42\t-9\t25\t48\t69\t85\t101\t115\t122\t134\t135\t131\t119\t109\t98\t84\t72\t56\t36\t16\t-7\t-24\t-39\t-46\t-55\t-63\t-68\t-71\t-79\t-78\t-67\t-55\t-41\t-27\t-17\t-11\t5\t17\t26\t39\t48\t59\t70\t63\t58\t54\t47\t38\t29\t16\t1\t-13\t-31\t-51\t-70\t-79\t-95\t-108\t-124\t-133\t-138\t-129\t-120\t-110\t-96\t-76\t-66\t-54\t-31\t0\t31\t58\t84\t104\t118\t134\t150\t167\t176\t182\t185\t175\t161\t135\t116\t98\t76\t46\t17\t-18\t-52\t-83\t-115\t-141\t-163\t-185\t-205\t-213\t-221\t-228\t-220\t-208\t-194\t-179\t-152\t-132\t-106\t-67\t-31\t11\t49\t86\t115\t137\t163\t184\t202\t225\t236\t236\t234\t225\t204\t183\t160\t134\t107\t78\t37\t2\t-34\t-67\t-103\t-129\t-159\t-187\t-207\t-227\t-235\t-240\t-236\t-226\t-218\t-199\t-177\t-159\t-124\t-93\t-60\t-27\t8\t35\t66\t99\t126\t148\t165\t180\t190\t191\t191\t178\t167\t157\t137\t120\t104\t77\t51\t27\t-4\t-32\t-54\t-77\t-94\t-112\t-125\t-132\t-137\t-128\t-129\t-132\t-126\t-117\t-107\t-86\t-65\t-46\t-27\t-7\t7\t18\t27\t36\t49\t59\t68\t76\t77\t73\t62\t50\t39\t32\t23\t13\t1\t-10\t-20\t-31\t-41\t-46\t-56\t-59\t-56\t-52\t-45\t-40\t-30\t-23\t-13\t2\t8\t15\t29\t44\t57\t68\t73\t72\t72\t71\t66\t60\t54\t48\t37\t21\t3\t-16\t-30\t-44\t-61\t-74\t-87\t-99\t-111\t-117\t-118\t-118\t-118\t-113\t-112\t-101\t-84\t-67\t-42\t-16\t5\t20\t36\t56\t72\t95\t110\t126\t138\t147\t149\t144\t144\t136\t126\t114\t100\t81\t63\t37\t4\t-23\t-49\t-73\t-94\t-107\t-124\t-138\t-150\t-156\t-161\t-160\t-156\t-150\t-137\t-122\t-109\t-87\t-63\t-41\t-19\t7\t29\t49\t73\t89\t114\t134\t143\t151\t150\t146\t141\t131\t125\t114\t101\t85\t66\t44\t20\t-3\t-22\t-43\t-61\t-70\t-81\t-94\t-104\t-116\t-118\t-119\t-116\t-109\t-97\t-85\t-68\t-51\t-37\t-29\t-13\t6\t14\t30\t47\t55\t65\t74\t80\t74\t75\t68\t61\t56\t48\t41\t28\t20\t5\t-11\t-20\t-35\t-38\t-46\t-56\t-56\t-59\t-56\t-57\t-49\t-39\t-37\t-25\t-10\t1\t9\t18\t27\t37\t50\t56\t60\t63\t72\t74\t74\t74\t62\t54\t41\t24\t7\t1\t-16\t-33\t-44\t-58\t-74\t-84\t-92\t-94\t-101\t-103\t-103\t-99\t-94\t-89\t-78\t-65\t-47\t-34\t-17\t4\t24\t41\t58\t71\t83\t95\t104\t111\t117\t117\t110\t111\t105\t94\t83\t64\t45\t26\t11\t-3\t-20\t-36\t-56\t-77\t-96\t-110\t-121\t-126\t-122\t-123\t-123\t-120\t-113\t-108\t-97\t-83\t-72\t-58\t-38\t-19\t-2\t16\t34\t46\t61\t76\t81\t86\t96\t99\t97\t99\t98\t85\t77\t73\t62\t49\t35\t23\t9\t-3\t-19\t-34\t-47\t-58\t-67\t-65\t-68\t-71\t-69\t-69\t-70\t-69\t-63\t-57\t-48\t-41\t-35\t-25\t-14\t-7\t-3\t5\t10\t7\t12\t16\t18\t12\t12\t13\t10\t10\t5\t-7\t-13\t-16\t-14\t-13\t-12\t-13\t-15\t-11\t-11\t-12\t-7\t-1\t8\t13\t20\t26\t31\t36\t37\t42\t47\t52\t54\t47\t44\t36\t30\t29\t20\t13\t3\t-12\t-28\t-39\t-52\t-64\t-77\t-88\t-100\t-105\t-106\t-107\t-106\t-105\t-102\t-94\t-89\t-82\t-67\t-49\t-33\t-14\t7\t29\t43\t56\t74\t90\t102\t112\t123\t131\t134\t135\t129\t123\t110\t90\t80\t65\t48\t31\t14\t-3\t-25\t-46\t-65\t-88\t-105\t-117\t-125\t-130\t-138\t-142\t-145\t-142\t-141\t-134\t-117\t-104\t-87\t-66\t-52\t-36\t-20\t-4\t19\t40\t58\t75\t90\t107\t115\t119\t115\t114\t111\t109\t107\t101\t91\t82\t69\t51\t39\t24\t3\t-14\t-19\t-32\t-41\t-54\t-63\t-79\t-85\t-91\t-93\t-90\t-98\t-93\t-90\t-83\t-81\t-77\t-66\t-59\t-53\t-42\t-35\t-25\t-18\t-15\t-9\t-3\t5\t9\t11\t13\t18\t27\t34\t43\t45\t44\t44\t47\t51\t56\t55\t60\t66\t61\t54\t52\t53\t54\t55\t49\t42\t34\t24\t14\t6\t-2\t-15\t-30\t-42\t-57\t-71\t-82\t-90\t-96\t-107\t-117\t-131\t-140\t-140\t-137\t-133\t-126\t-118\t-107\t-94\t-83\t-70\t-49\t-22\t3\t27\t51\t75\t95\t118\t134\t147\t161\t177\t188\t190\t191\t187\t179\t169\t148\t130\t106\t79\t56\t30\t-1\t-35\t-64\t-91\t-123\t-153\t-178\t-199\t-216\t-230\t-234\t-244\t-250\t-250\t-247\t-232\t-204\t-178\t-148\t-115\t-85\t-53\t-17\t15\t50\t90\t132\t166\t194\t215\t234\t252\t263\t270\t268\t261\t249\t235\t215\t190\t157\t123\t90\t50\t7\t-30\t-65\t-103\t-139\t-169\t-203\t-230\t-255\t-272\t-283\t-290\t-289\t-279\t-272\t-265\t-247\t-223\t-193\t-162\t-123\t-82\t-44\t-4\t37\t70\t109\t141\t173\t203\t229\t246\t261\t270\t278\t278\t267\t251\t234\t210\t187\t164\t142\t116\t76\t38\t3\t-33\t-71\t-102\t-137\t-170\t-194\t-213\t-229\t-251\t-260\t-265\t-267\t-262\t-255\t-248\t-233\t-209\t-190\t-173\t-144\t-110\t-82\t-51\t-19\t16\t47\t81\t110\t137\t163\t186\t206\t224\t237\t249\t255\t257\t254\t246\t233\t213\t198\t181\t161\t135\t107\t72\t36\t2\t-38\t-75\t-107\t-140\t-173\t-203\t-226\t-247\t-269\t-282\t-298\t-317\t-316\t-318\t-304\t-285\t-266\t-243\t-224\t-193\t-158\t-122\t-79\t-36\t8\t50\t98\t138\t181\t223\t257\t289\t318\t342\t353\t364\t374\t374\t374\t361\t338\t306\t276\t234\t186\t133\t79\t31\t-26\t-78\t-136\t-192\t-242\t-292\t-340\t-379\t-465\t-471\t-477\t-480\t-481\t-477\t-460\t-434\t-404\t-367\t-324\t-246\t-171\t-165\t-143\t-92\t-24\t52\t132\t211\t293\t364\t433\t490\t535\t579\t605\t621\t622\t617\t590\t557\t511\t459\t392\t320\t241\t159\t64\t-27\t-115\t-201\t-291\t-381\t-460\t-530\t-593\t-641\t-682\t-714\t-734\t-741\t-732\t-712\t-683\t-644\t-587\t-517\t-441\t-356\t-258\t-161\t-57\t45\t146\t252\t351\t445\t534\t613\t704\t787\t814\t835\t839\t838\t824\t797\t760\t703\t635\t553\t461\t360\t255\t142\t27\t-91\t-209\t-322\t-476\t-585\t-664\t-743\t-814\t-872\t-918\t-945\t-958\t-955\t-943\t-907\t-866\t-798\t-717\t-623\t-522\t-405\t-278\t-149\t-15\t119\t259\t394\t511\t625\t776\t872\t945\t999\t1045\t1072\t1090\t1085\t1058\t1015\t954\t878\t786\t675\t554\t419\t273\t124\t-23\t-180\t-330\t-534\t-671\t-792\t-903\t-1003\t-1085\t-1153\t-1207\t-1233\t-1244\t-1233\t-1206\t-1147\t-1072\t-977\t-855\t-727\t-582\t-426\t-257\t-85\t88\t263\t436\t597\t791\t934\t1041\t1136\t1228\t1302\t1352\t1372\t1370\t1344\t1294\t1221\t1130\t1015\t877\t726\t566\t392\t204\t9\t-182\t-380\t-622\t-776\t-925\t-1062\t-1186\t-1295\t-1380\t-1437\t-1481\t-1499\t-1487\t-1451\t-1388\t-1293\t-1181\t-1048\t-897\t-728\t-544\t-352\t-149\t53\t256\t461\t669\t898\t1039\t1174\t1296\t1399\t1476\t1532\t1569\t1579\t1560\t1513\t1437\t1332\t1208\t1065\t903\t714\t512\t309\t93\t-120\t-333\t-605\t-786\t-954\t-1123\t-1264\t-1386\t-1496\t-1584\t-1642\t-1669\t-1664\t-1633\t-1580\t-1497\t-1388\t-1256\t-1107\t-929\t-737\t-528\t-319\t-103\t117\t336\t555\t797\t1003\t1164\t1312\t1446\t1557\t1638\t1698\t1734\t1738\t1706\t1654\t1571\t1463\t1328\t1163\t985\t794\t579\t359\t123\t-118\t-356\t-643\t-837\t-1020\t-1199\t-1360\t-1509\t-1640\t-1740\t-1804\t-1844\t-1853\t-1832\t-1775\t-1693\t-1580\t-1436\t-1267\t-1079\t-871\t-651\t-415\t-180\t68\t322\t566\t849\t1075\t1267\t1444\t1592\t1728\t1844\t1918\t1969\t1983\t1963\t1910\t1825\t1706\t1558\t1385\t1187\t964\t718\t459\t186\t-83\t-356\t-683\t-921\t-1143\t-1354\t-1552\t-1730\t-1884\t-2005\t-2098\t-2148\t-2162\t-2136\t-2078\t-1986\t-1854\t-1694\t-1498\t-1277\t-1034\t-774\t-499\t-211\t83\t379\t678\t1004\t1250\t1478\t1692\t1882\t2041\t2160\t2254\t2309\t2321\t2292\t2223\t2115\t1967\t1793\t1582\t1343\t1075\t786\t482\t168\t-145\t-494\t-820\t-1096\t-1365\t-1617\t-1850\t-2045\t-2214\t-2340\t-2427\t-2477\t-2485\t-2451\t-2366\t-2240\t-2073\t-1780\t-1244\t-833\t-512\t-242\t5\t236\t448\t668\t927\t1106\t1267\t1429\t1580\t1701\t1808\t1888\t1935\t1956\t1946\t1907\t1830\t1722\t1593\t1436\t1253\t1049\t821\t574\t326\t68\t-192\t-475\t-744\t-956\t-1164\t-1356\t-1534\t-1685\t-1808\t-1904\t-1970\t-2000\t-1988\t-1944\t-1868\t-1762\t-1628\t-1469\t-1271\t-1054\t-828\t-574\t-311\t-42\t225\t483\t766\t1033\t1235\t1426\t1596\t1744\t1874\t1966\t2030\t2050\t2035\t1990\t1916\t1808\t1668\t1496\t1294\t1071\t826\t566\t299\t30\t-246\t-566\t-833\t-1055\t-1269\t-1474\t-1662\t-1819\t-1946\t-2040\t-2098\t-2126\t-2117\t-2070\t-1984\t-1867\t-1722\t-1541\t-1325\t-1092\t-847\t-592\t-320\t-33\t248\t532\t850\t1113\t1332\t1534\t1718\t1881\t2014\t2108\t2166\t2195\t2184\t2136\t2045\t1920\t1763\t1574\t1362\t1128\t868\t590\t305\t15\t-280\t-626\t-892\t-1136\t-1373\t-1595\t-1790\t-1958\t-2092\t-2191\t-2256\t-2285\t-2268\t-2215\t-2126\t-1999\t-1829\t-1631\t-1411\t-1161\t-896\t-615\t-322\t-17\t292\t590\t933\t1190\t1426\t1647\t1846\t2014\t2145\t2249\t2317\t2338\t2323\t2262\t2167\t2037\t1866\t1665\t1434\t1174\t896\t605\t300\t-8\t-318\t-692\t-962\t-1225\t-1477\t-1702\t-1900\t-2075\t-2217\t-2322\t-2384\t-2408\t-2384\t-2329\t-2230\t-2086\t-1905\t-1698\t-1463\t-1201\t-912\t-617\t-305\t12\t324\t638\t1002\t1262\t1512\t1743\t1950\t2122\t2267\t2371\t2433\t2452\t2429\t2368\t2266\t2117\t1938\t1725\t1478\t1208\t922\t614\t289\t-34\t-368\t-738\t-1026\t-1303\t-1564\t-1800\t-2013\t-2193\t-2334\t-2438\t-2496\t-2517\t-2499\t-2429\t-2322\t-2171\t-1983\t-1763\t-1514\t-1236\t-937\t-622\t-294\t36\t369\t717\t1065\t1347\t1612\t1851\t2061\t2241\t2382\t2486\t2551\t2568\t2547\t2484\t2368\t2216\t2025\t1797\t1538\t1253\t942\t617\t285\t-58\t-420\t-797\t-1097\t-1382\t-1649\t-1903\t-2127\t-2315\t-2465\t-2566\t-2627\t-2643\t-2614\t-2542\t-2424\t-2264\t-2068\t-1836\t-1566\t-1273\t-959\t-624\t-282\t64\t414\t787\t1138\t1437\t1712\t1962\t2183\t2361\t2510\t2621\t2683\t2696\t2662\t2585\t2468\t2302\t2093\t1847\t1578\t1278\t956\t612\t253\t-106\t-494\t-860\t-1174\t-1479\t-1765\t-2025\t-2253\t-2440\t-2588\t-2683\t-2740\t-2747\t-2713\t-2626\t-2501\t-2329\t-2116\t-1866\t-1588\t-1277\t-945\t-594\t-236\t128\t489\t890\t1230\t1532\t1812\t2070\t2291\t2481\t2630\t2730\t2782\t2789\t2743\t2651\t2516\t2339\t2122\t1863\t1574\t1260\t920\t564\t199\t-169\t-585\t-945\t-1267\t-1576\t-1863\t-2122\t-2349\t-2536\t-2683\t-2781\t-2828\t-2833\t-2785\t-2688\t-2547\t-2366\t-2138\t-1873\t-1578\t-1255\t-915\t-555\t-186\t187\t561\t984\t1310\t1613\t1896\t2150\t2378\t2568\t2707\t2809\t2862\t2865\t2818\t2718\t2568\t2383\t2152\t1883\t1583\t1251\t901\t536\t162\t-215\t-645\t-1001\t-1337\t-1647\t-1937\t-2203\t-2433\t-2623\t-2763\t-2859\t-2911\t-2907\t-2853\t-2755\t-2605\t-2408\t-2168\t-1898\t-1597\t-1265\t-909\t-535\t-156\t227\t611\t1039\t1372\t1688\t1986\t2249\t2473\t2657\t2804\t2901\t2948\t2944\t2889\t2779\t2627\t2426\t2187\t1916\t1605\t1257\t890\t509\t119\t-270\t-720\t-1073\t-1413\t-1743\t-2045\t-2314\t-2545\t-2733\t-2872\t-2964\t-3007\t-2999\t-2936\t-2824\t-2658\t-2450\t-2202\t-1913\t-1591\t-1242\t-874\t-490\t-92\t311\t722\t1140\t1477\t1802\t2105\t2369\t2591\t2780\t2920\t3007\t3047\t3026\t2955\t2837\t2665\t2451\t2196\t1898\t1564\t1212\t831\t435\t35\t-386\t-831\t-1186\t-1536\t-1865\t-2163\t-2428\t-2653\t-2839\t-2972\t-3052\t-3083\t-3061\t-2980\t-2850\t-2669\t-2446\t-2181\t-1878\t-1539\t-1172\t-785\t-386\t18\t423\t865\t1252\t1591\t1913\t2208\t2470\t2692\t2862\t2990\t3064\t3088\t3056\t2976\t2837\t2652\t2415\t2140\t1831\t1488\t1117\t737\t338\t-72\t-513\t-926\t-1285\t-1635\t-1958\t-2253\t-2505\t-2724\t-2892\t-3004\t-3068\t-3091\t-3051\t-2957\t-2811\t-2621\t-2386\t-2110\t-1794\t-1448\t-1079\t-687\t-293\t106\t514\t964\t1332\t1673\t1985\t2267\t2516\t2725\t2890\t3002\t3060\t3072\t3027\t2928\t2782\t2584\t2339\t2062\t1753\t1408\t1036\t648\t245\t-158\t-613\t-1002\t-1356\t-1698\t-2016\t-2294\t-2543\t-2745\t-2901\t-3008\t-3064\t-3064\t-3017\t-2917\t-2765\t-2563\t-2323\t-2037\t-1717\t-1367\t-995\t-608\t-208\t194\t594\t1043\t1395\t1724\t2031\t2307\t2547\t2743\t2892\t2993\t3047\t3045\t2987\t2880\t2723\t2522\t2281\t1999\t1680\t1333\t958\t569\t170\t-235\t-693\t-1061\t-1408\t-1742\t-2044\t-2320\t-2556\t-2747\t-2892\t-2997\t-3043\t-3034\t-2980\t-2868\t-2705\t-2496\t-2250\t-1958\t-1637\t-1289\t-922\t-536\t-140\t257\t664\t1094\t1430\t1753\t2051\t2318\t2550\t2739\t2878\t2967\t3008\t3000\t2939\t2821\t2660\t2453\t2204\t1919\t1595\t1246\t877\t493\t100\t-292\t-750\t-1107\t-1450\t-1770\t-2071\t-2334\t-2556\t-2733\t-2868\t-2952\t-2986\t-2969\t-2900\t-2783\t-2618\t-2407\t-2156\t-1867\t-1544\t-1198\t-836\t-450\t-64\t327\t728\t1133\t1465\t1774\t2066\t2321\t2537\t2705\t2838\t2914\t2954\t2936\t2861\t2739\t2570\t2354\t2100\t1813\t1491\t1143\t782\t395\t12\t-385\t-807\t-1147\t-1475\t-1783\t-2067\t-2320\t-2533\t-2696\t-2822\t-2897\t-2918\t-2893\t-2816\t-2692\t-2523\t-2306\t-2050\t-1765\t-1445\t-1099\t-740\t-369\t12\t393\t797\t1174\t1492\t1789\t2065\t2302\t2505\t2668\t2787\t2859\t2878\t2845\t2760\t2633\t2462\t2248\t1995\t1702\t1382\t1048\t684\t317\t-59\t-465\t-855\t-1182\t-1498\t-1792\t-2062\t-2297\t-2490\t-2647\t-2754\t-2814\t-2828\t-2796\t-2712\t-2585\t-2410\t-2191\t-1934\t-1649\t-1332\t-990\t-636\t-273\t95\t458\t861\t1211\t1511\t1799\t2056\t2273\t2461\t2602\t2705\t2760\t2769\t2727\t2640\t2508\t2330\t2116\t1859\t1574\t1265\t932\t583\t222\t-144\t-547\t-904\t-1212\t-1508\t-1788\t-2036\t-2253\t-2434\t-2569\t-2665\t-2712\t-2714\t-2665\t-2570\t-2431\t-2254\t-2034\t-1780\t-1497\t-1193\t-861\t-520\t-175\t174\t531\t918\t1238\t1522\t1785\t2021\t2219\t2384\t2514\t2600\t2634\t2624\t2574\t2482\t2341\t2161\t1946\t1702\t1421\t1115\t792\t458\t115\t-223\t-615\t-932\t-1222\t-1506\t-1764\t-1990\t-2184\t-2344\t-2461\t-2540\t-2577\t-2565\t-2504\t-2402\t-2261\t-2081\t-1863\t-1617\t-1346\t-1046\t-731\t-404\t-77\t257\t581\t954\t1239\t1497\t1740\t1957\t2137\t2284\t2393\t2459\t2484\t2470\t2412\t2313\t2172\t1990\t1779\t1538\t1272\t979\t670\t356\t35\t-291\t-675\t-958\t-1224\t-1482\t-1713\t-1920\t-2095\t-2231\t-2334\t-2393\t-2414\t-2393\t-2330\t-2226\t-2085\t-1914\t-1703\t-1463\t-1200\t-915\t-622\t-317\t-6\t308\t613\t971\t1229\t1468\t1681\t1884\t2049\t2178\t2265\t2320\t2333\t2307\t2242\t2133\t1993\t1822\t1616\t1380\t1123\t845\t553\t255\t-48\t-364\t-707\t-963\t-1215\t-1446\t-1661\t-1847\t-2001\t-2123\t-2209\t-2255\t-2260\t-2226\t-2159\t-2059\t-1917\t-1742\t-1534\t-1295\t-1038\t-769\t-487\t-199\t96\t391\t676\t994\t1229\t1449\t1647\t1817\t1954\t2063\t2139\t2177\t2178\t2140\t2062\t1955\t1810\t1637\t1430\t1203\t956\t694\t418\t135\t-150\t-463\t-760\t-998\t-1220\t-1432\t-1619\t-1780\t-1911\t-2015\t-2077\t-2110\t-2102\t-2055\t-1975\t-1858\t-1710\t-1531\t-1330\t-1103\t-862\t-607\t-344\t-72\t198\t467\t746\t1031\t1237\t1427\t1599\t1745\t1859\t1947\t1995\t2019\t2006\t1955\t1868\t1753\t1600\t1425\t1219\t997\t762\t518\t254\t-8\t-267\t-577\t-808\t-1022\t-1225\t-1410\t-1573\t-1706\t-1807\t-1885\t-1927\t-1938\t-1911\t-1854\t-1762\t-1640\t-1489\t-1314\t-1120\t-905\t-668\t-432\t-182\t72\t318\t555\t826\t1054\t1234\t1398\t1536\t1650\t1744\t1805\t1836\t1834\t1803\t1740\t1650\t1526\t1381\t1212\t1013\t800\t576\t338\t101\t-137\t-391\t-658\t-849\t-1037\t-1211\t-1367\t-1509\t-1613\t-1692\t-1738\t-1760\t-1752\t-1713\t-1644\t-1544\t-1418\t-1269\t-1098\t-909\t-703\t-484\t-262\t-36\t190\t413\t632\t890\t1063\t1214\t1350\t1467\t1560\t1626\t1672\t1680\t1663\t1616\t1537\t1437\t1310\t1161\t990\t801\t601\t395\t178\t-39\t-260\t-522\t-721\t-890\t-1053\t-1198\t-1329\t-1439\t-1521\t-1579\t-1611\t-1610\t-1583\t-1522\t-1439\t-1332\t-1202\t-1058\t-891\t-702\t-506\t-307\t-98\t111\t318\t520\t724\t938\t1084\t1213\t1324\t1413\t1475\t1519\t1536\t1521\t1481\t1420\t1335\t1227\t1096\t945\t778\t599\t409\t215\t15\t-189\t-406\t-633\t-783\t-930\t-1066\t-1191\t-1290\t-1377\t-1439\t-1470\t-1472\t-1454\t-1406\t-1339\t-1239\t-1121\t-990\t-839\t-672\t-498\t-311\t-118\t67\t260\t443\t617\t825\t976\t1087\t1188\t1274\t1341\t1385\t1406\t1398\t1368\t1312\t1236\t1138\t1019\t886\t738\t573\t404\t225\t37\t-153\t-337\t-576\t-710\t-841\t-965\t-1079\t-1172\t-1252\t-1311\t-1345\t-1363\t-1349\t-1305\t-1241\t-1159\t-1060\t-942\t-804\t-652\t-483\t-313\t-138\t35\t213\t387\t553\t723\t907\t1011\t1108\t1186\t1248\t1288\t1310\t1308\t1283\t1233\t1168\t1079\t971\t841\t703\t553\t393\t225\t57\t-122\t-288\t-506\t-655\t-782\t-905\t-1014\t-1101\t-1177\t-1232\t-1263\t-1275\t-1263\t-1231\t-1176\t-1104\t-1011\t-906\t-771\t-624\t-463\t-301\t-138\t31\t199\t362\t523\t669\t857\t961\t1047\t1121\t1186\t1225\t1243\t1240\t1221\t1175\t1106\t1025\t924\t805\t676\t532\t376\t213\t50\t-118\t-278\t-481\t-631\t-749\t-863\t-967\t-1055\t-1129\t-1180\t-1212\t-1228\t-1213\t-1180\t-1129\t-1059\t-964\t-855\t-729\t-595\t-443\t-286\t-127\t29\t195\t352\t505\t647\t820\t931\t1012\t1085\t1141\t1177\t1196\t1197\t1178\t1138\t1074\t999\t900\t781\t650\t509\t359\t207\t44\t-117\t-278\t-477\t-624\t-733\t-844\t-941\t-1026\t-1094\t-1144\t-1174\t-1189\t-1176\t-1147\t-1095\t-1021\t-932\t-831\t-710\t-577\t-434\t-281\t-127\t26\t187\t342\t489\t630\t796\t918\t996\t1062\t1112\t1153\t1170\t1167\t1149\t1103\t1050\t974\t877\t767\t642\t504\t359\t211\t51\t-101\t-254\t-438\t-600\t-715\t-827\t-918\t-998\t-1062\t-1115\t-1151\t-1166\t-1152\t-1126\t-1076\t-1010\t-929\t-828\t-707\t-577\t-432\t-287\t-137\t14\t172\t317\t460\t596\t741\t889\t964\t1032\t1088\t1125\t1150\t1153\t1133\t1097\t1040\t965\t870\t766\t649\t519\t383\t233\t82\t-69\t-223\t-389\t-571\t-679\t-782\t-874\t-963\t-1032\t-1087\t-1126\t-1145\t-1143\t-1119\t-1072\t-1010\t-930\t-836\t-725\t-607\t-463\t-319\t-177\t-28\t123\t271\t417\t559\t696\t869\t945\t1012\t1067\t1111\t1134\t1140\t1127\t1094\t1044\t976\t888\t788\t673\t552\t414\t267\t118\t-34\t-186\t-331\t-539\t-645\t-752\t-847\t-936\t-1010\t-1072\t-1113\t-1138\t-1134\t-1115\t-1079\t-1022\t-947\t-855\t-747\t-632\t-503\t-362\t-217\t-67\t77\t223\t373\t511\t644\t802\t909\t983\t1042\t1085\t1113\t1131\t1126\t1103\t1059\t993\t915\t822\t709\t587\t458\t320\t170\t20\t-132\t-273\t-461\t-605\t-712\t-807\t-896\t-972\t-1038\t-1083\t-1117\t-1128\t-1120\t-1090\t-1044\t-980\t-892\t-788\t-679\t-556\t-419\t-278\t-128\t19\t167\t318\t459\t588\t724\t877\t948\t1009\t1054\t1091\t1115\t1120\t1104\t1072\t1016\t943\t859\t754\t634\t510\t374\t234\t92\t-58\t-205\t-352\t-545\t-651\t-753\t-847\t-935\t-1004\t-1059\t-1095\t-1118\t-1112\t-1089\t-1051\t-995\t-920\t-827\t-723\t-604\t-477\t-344\t-202\t-58\t88\t230\t376\t516\t644\t801\t904\t969\t1023\t1068\t1100\t1109\t1104\t1077\t1030\t967\t895\t801\t692\t570\t438\t299\t156\t12\t-130\t-270\t-453\t-593\t-693\t-788\t-879\t-955\t-1020\t-1065\t-1091\t-1097\t-1088\t-1062\t-1016\t-947\t-867\t-770\t-662\t-539\t-406\t-266\t-126\t19\t163\t305\t440\t569\t686\t854\t919\t982\t1034\t1070\t1090\t1096\t1079\t1047\t996\t925\t833\t732\t622\t496\t366\t232\t94\t-51\t-196\t-341\t-542\t-640\t-736\t-821\t-901\t-971\t-1020\t-1060\t-1076\t-1079\t-1061\t-1025\t-966\t-897\t-808\t-704\t-591\t-468\t-332\t-195\t-57\t84\t227\t365\t493\t613\t744\t876\t937\t987\t1027\t1052\t1062\t1062\t1042\t1003\t941\t867\t777\t670\t550\t430\t298\t165\t26\t-113\t-250\t-414\t-569\t-661\t-752\t-836\t-912\t-973\t-1019\t-1041\t-1047\t-1042\t-1017\t-974\t-913\t-834\t-744\t-639\t-530\t-399\t-266\t-127\t8\t137\t272\t400\t519\t633\t775\t882\t936\t984\t1016\t1031\t1036\t1022\t992\t943\t878\t798\t710\t606\t495\t374\t247\t112\t-25\t-1

In [25]:
from datetime import datetime

timestamp = 1953125
datetime.fromtimestamp(timestamp)

datetime.datetime(1970, 1, 23, 15, 32, 5)

In [22]:
from datetime import datetime
from datetime import timedelta

date_time = datetime.now() - timedelta(days=4)
time_stamp = datetime.timestamp(date_time)
time_stamp

1668765883.336915

In [24]:
180 * 60 + 1668765883

1668776683

In [30]:
with open("Wall_test4_adc.txt") as f:
    w = f.readlines()

In [31]:
len(w)

8

In [38]:
splitted_data = w[1].replace(",", ".").split("\t")

In [39]:
len(splitted_data)

16404

In [3]:
import pandas as pd

df = pd.read_fwf('Wall_test4_adc.txt')
print(df.shape)

(7, 133)

In [4]:
import pandas as pd

df = pd.read_fwf('Wall_test4_adc.txt', header=None)
print(df.shape)

(8, 133)

In [7]:
df

,0,1,2,3,4,5,6,7,8,9,...,123,124,125,126,127,128,129,130,131,132
0,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-127.0,-126.0,-124.0,-123.0,-122.0,-126.0,-126.0,-123.0,-123.0,-122.0
2,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = pd.read_csv("Wall_test4_adc.txt", header=None, sep="\t")

In [13]:
df.iloc[:, 16380: 16385]

   16380  16381  16382  16383  16384
0   -163   -159   -154   -150   -151
1   -155   -155   -157   -155   -150
2   -153   -158   -164   -174   -176
3   -176   -172   -171   -166   -167
4   -159   -159   -156   -155   -155
5   -224   -226   -227   -231   -232
6   -130   -133   -136   -136   -135
7   -130   -133   -136   -136   -135

In [ ]:
df.iloc[:, :20]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,19,16384,0,0,0,1,"119,2093",0,1953125,12,0,0,"0,8939796",4096,"293,6013","0,22",0,0,38682,-155
1,19,16384,0,0,0,1,"119,2093",0,1953125,12,0,0,"0,888979",4096,"293,6013","0,22",0,0,38683,-123
2,19,16384,0,0,0,1,"119,2093",0,1953125,12,0,0,"0,8909792",4096,"293,6013","0,22",0,0,38683,-162
3,19,16384,0,0,0,1,"119,2093",0,1953125,12,0,0,"0,8956941",4096,"293,6013","0,22",0,0,38683,-147
4,19,16384,0,0,0,1,"119,2093",0,1953125,12,0,0,"0,9011233",4096,"293,6013","0,22",0,0,38683,-164
5,19,16384,0,0,0,1,"119,2093",0,1953125,12,0,0,"0,9095531",4096,"293,6013","0,22",0,0,38684,-221
6,19,16384,0,0,0,1,"119,2093",0,1953125,12,0,0,"0,9102674",4096,"293,6013","0,22",0,0,38684,-145
7,19,16384,0,0,0,1,"119,2093",0,1953125,12,0,0,"0,9102674",4096,"293,6013","0,22",0,0,38684,-145

### Seconds from midnight

In [32]:
from datetime import datetime

now = datetime.now()

seconds_since_midnight = (now - now.replace(hour=0, minute=0, second=0)).total_seconds()
print(seconds_since_midnight)

25567.0

In [33]:
seconds = seconds_since_midnight % 60
total_minutes = seconds_since_midnight // 60
minutes = total_minutes % 60
hour = total_minutes // 60

print(f"{hour} : {minutes} : {seconds}")

7.0 : 6.0 : 7.0

In [2]:
total_sec = 58712
seconds = total_sec % 60
total_minutes = total_sec // 60
minutes = total_minutes % 60
hour = total_minutes // 60

print(f"{hour} : {minutes} : {seconds}")

16 : 18 : 32

In [3]:
total_sec = 62306
seconds = total_sec % 60
total_minutes = total_sec // 60
minutes = total_minutes % 60
hour = total_minutes // 60

print(f"{hour} : {minutes} : {seconds}")

17 : 18 : 26

from datetime import datetime, timezone

print(datetime.now(), datetime.now(timezone.utc))

In [ ]:
from datetime import datetime, timezone
import json
import time

run_loop = True
now = datetime.now()
reference_second = (now - now.replace(hour=0, minute=0, second=0)).total_seconds()
time_stamp = []
while run_loop:
    local_now = datetime.now()
    seconds_since_midnight_local = (local_now - local_now.replace(hour=0, minute=0, second=0)).total_seconds()
    
    utc_now = datetime.now(timezone.utc)
    seconds_since_midnight_utc = (utc_now - utc_now.replace(hour=0, minute=0, second=0)).total_seconds()
    z
    
    dict_data = {
    "local_timestamp": seconds_since_midnight_local,
    "utc_timestamp": seconds_since_midnight_utc 
    }
    time_stamp.append(dict_data)
    print(seconds_since_midnight_local)
    time.sleep(1)
    if (seconds_since_midnight_local - reference_second) >= 130:
        with open("timestamp_for_project_final.json", "w", encoding="utf-8") as f:
            json.dump(time_stamp, f, ensure_ascii=False, indent=4)
        run_loop = False

In [11]:
import pandas as pd

df = pd.read_json('experimental_data/prediction_result_2511_test6_with_timestamp.json')
print(df.shape)

(177, 3)

In [12]:
df.head()

   total_count  timestamp prediction
0          177      59380      chair
1          176      59380      chair
2          175      59378      chair
3          174      59376      chair
4          173      59375      chair

In [9]:
df.iloc[0, 1]

59704

In [13]:
df.loc[:, "timestamp"]

0      59380
1      59380
2      59378
3      59376
4      59375
       ...
172    59172
173    59171
174    59171
175    59170
176    59169
Name: timestamp, Length: 177, dtype: int64

In [14]:
df.describe()

       total_count     timestamp
count   177.000000    177.000000
mean     89.000000  59274.463277
std      51.239633     63.142246
min       1.000000  59169.000000
25%      45.000000  59218.000000
50%      89.000000  59282.000000
75%     133.000000  59328.000000
max     177.000000  59380.000000

In [15]:
df.loc[:, "timestamp"].apply(lambda x: x - 3600)

0      55780
1      55780
2      55778
3      55776
4      55775
       ...
172    55572
173    55571
174    55571
175    55570
176    55569
Name: timestamp, Length: 177, dtype: int64

In [18]:
df_test6_prediction = df.copy()

In [19]:
df_test6_prediction["timestamp"] = df.loc[:, "timestamp"].apply(lambda x: x - 3600)

In [20]:
df_test6_prediction

     total_count  timestamp prediction
0            177      55780      chair
1            176      55780      chair
2            175      55778      chair
3            174      55776      chair
4            173      55775      chair
..           ...        ...        ...
172            5      55572     person
173            4      55571     person
174            3      55571     person
175            2      55570     person
176            1      55569     person

[177 rows x 3 columns]

In [21]:
df

     total_count  timestamp prediction
0            177      59380      chair
1            176      59380      chair
2            175      59378      chair
3            174      59376      chair
4            173      59375      chair
..           ...        ...        ...
172            5      59172     person
173            4      59171     person
174            3      59171     person
175            2      59170     person
176            1      59169     person

[177 rows x 3 columns]

In [29]:
import pandas as pd

df_experiment = pd.read_csv('experimental_data/Wall_test6.txt', header=None, sep="\t")
print(df_experiment.shape)

(800, 16404)

In [30]:
df_experiment.head()

,0,1,2,3,4,5,6,7,8,9,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,19,16384,0,0,1,1,"119,2093",0,1953125,12,...,-150,-154,-150,-155,-159,-166,-167,-169,-162,NaN
1,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-179,-177,-178,-176,-173,-172,-168,-166,-167,NaN
2,19,16384,0,0,1,1,"119,2093",0,1953125,12,...,-144,-145,-146,-144,-146,-141,-143,-149,-152,NaN
3,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-157,-159,-163,-162,-163,-159,-159,-157,-156,NaN
4,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-149,-144,-147,-148,-154,-149,-144,-150,-148,NaN

In [34]:
df_experiment.drop([16403,], axis=1, inplace=True)

In [35]:
df_experiment

,0,1,2,3,4,5,6,7,8,9,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,19,16384,0,0,1,1,"119,2093",0,1953125,12,...,-146,-150,-154,-150,-155,-159,-166,-167,-169,-162
1,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
2,19,16384,0,0,1,1,"119,2093",0,1953125,12,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
3,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
4,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
796,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
797,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
798,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
799,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137

In [38]:
df_experiment.isna().sum().sum()

0

In [44]:
df_test6_prediction.columns

Index(['total_count', 'timestamp', 'prediction'], dtype='object')

In [45]:
df_test6_prediction.shape

(177, 3)

In [46]:
df_experiment.shape

(800, 16403)

In [47]:
df_experiment.columns

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            16393, 16394, 16395, 16396, 16397, 16398, 16399, 16400, 16401,
            16402],
           dtype='int64', length=16403)

In [49]:
df_experiment.index

RangeIndex(start=0, stop=800, step=1)

In [55]:
import numpy as np

np.where(df_experiment == 55760)  # first is row, second is column

(array([770, 771, 772, 773, 774, 775, 776], dtype=int64),
 array([18, 18, 18, 18, 18, 18, 18], dtype=int64))

In [56]:
df_experiment.iloc[:, 18]

0      55593
1      55594
2      55594
3      55594
4      55594
       ...
795    55763
796    55763
797    55764
798    55764
799    55764
Name: 18, Length: 800, dtype: int64

In [58]:
df_experimental_data = df_experiment.iloc[:, 18:]

In [60]:
df_experimental_data

,18,19,20,21,22,23,24,25,26,27,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,55593,-167,-168,-169,-169,-169,-161,41,73,94,...,-146,-150,-154,-150,-155,-159,-166,-167,-169,-162
1,55594,-162,-164,-160,-153,-151,-147,-456,-502,-542,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
2,55594,-153,-153,-154,-150,-150,-153,-168,-169,-169,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
3,55594,-158,-158,-159,-158,-156,-404,-454,-494,-539,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
4,55594,-149,-150,-148,-146,-148,-144,-219,-280,-346,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,55763,-162,-169,-162,-162,-161,-161,-87,-154,-218,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
796,55763,-162,-169,-162,-162,-161,-161,-87,-154,-218,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
797,55764,-135,-133,-132,-129,-131,-568,-533,-491,-436,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
798,55764,-133,-139,-141,-141,-143,-495,-486,-461,-422,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
799,55764,-142,-143,-138,-142,-142,96,63,22,-26,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137

In [112]:
df_test6_prediction

     total_count  timestamp prediction
0            177      55780      chair
1            176      55780      chair
2            175      55778      chair
3            174      55776      chair
4            173      55775      chair
..           ...        ...        ...
172            5      55572     person
173            4      55571     person
174            3      55571     person
175            2      55570     person
176            1      55569     person

[177 rows x 3 columns]

In [62]:
df1 = pd.DataFrame([[1,2,3], [4,5,6]])

In [63]:
df1

   0  1  2
0  1  2  3
1  4  5  6

In [64]:
df2 = pd.DataFrame([[1,11,111], [4,15,16]])

In [65]:
df2

   0   1    2
0  1  11  111
1  4  15   16

In [69]:
df2.merge(df1, how='right')

   0  1  2
0  1  2  3
1  4  5  6

In [70]:
df2.merge(df1, how='left')

   0   1    2
0  1  11  111
1  4  15   16

In [71]:
df3 = pd.DataFrame([[1,11,111], [4,15,16], [5, 15, 28]])

In [72]:
df3

   0   1    2
0  1  11  111
1  4  15   16
2  5  15   28

In [75]:
df3.merge(df2, how='right')

   0   1    2
0  1  11  111
1  4  15   16

In [78]:
df3.merge(df2, how='left')

   0   1    2
0  1  11  111
1  4  15   16
2  5  15   28

In [79]:
df3.merge(df2, how='inner')

   0   1    2
0  1  11  111
1  4  15   16

In [80]:
df3.merge(df2, how='left', on=0)

   0  1_x  2_x   1_y    2_y
0  1   11  111  11.0  111.0
1  4   15   16  15.0   16.0
2  5   15   28   NaN    NaN

In [85]:
df3 = pd.DataFrame([[1,-14,101], [4,105,106], [5, 15, 28]])

In [86]:
df3.columns

RangeIndex(start=0, stop=3, step=1)

In [87]:
df3.columns = ['a', 'b', 'c']

In [88]:
df3

   a    b    c
0  1  -14  101
1  4  105  106
2  5   15   28

In [89]:
df2

   0   1    2
0  1  11  111
1  4  15   16

In [96]:
df3.columns = [0, 'b', 'c']

In [97]:
df3.merge(df2, how='inner')

   0    b    c   1    2
0  1  -14  101  11  111
1  4  105  106  15   16

In [98]:
df3.iloc[2, : ] = [4, 44, 444]

In [99]:
df3

   0    b    c
0  1  -14  101
1  4  105  106
2  4   44  444

In [100]:
df3.merge(df2)

   0    b    c   1    2
0  1  -14  101  11  111
1  4  105  106  15   16
2  4   44  444  15   16

In [103]:
display(df3)

   0    b    c
0  1  -14  101
1  4  105  106
2  4   44  444

In [109]:
df_experimental_data.rename(columns={18: "timestamp"}, inplace=True)

In [110]:
df_experimental_data

,timestamp,19,20,21,22,23,24,25,26,27,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,55593,-167,-168,-169,-169,-169,-161,41,73,94,...,-146,-150,-154,-150,-155,-159,-166,-167,-169,-162
1,55594,-162,-164,-160,-153,-151,-147,-456,-502,-542,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
2,55594,-153,-153,-154,-150,-150,-153,-168,-169,-169,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
3,55594,-158,-158,-159,-158,-156,-404,-454,-494,-539,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
4,55594,-149,-150,-148,-146,-148,-144,-219,-280,-346,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,55763,-162,-169,-162,-162,-161,-161,-87,-154,-218,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
796,55763,-162,-169,-162,-162,-161,-161,-87,-154,-218,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
797,55764,-135,-133,-132,-129,-131,-568,-533,-491,-436,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
798,55764,-133,-139,-141,-141,-143,-495,-486,-461,-422,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
799,55764,-142,-143,-138,-142,-142,96,63,22,-26,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137

In [111]:
df_test6_prediction.merge(df_experimental_data)

,total_count,timestamp,prediction,19,20,21,22,23,24,25,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,166,55764,chair,-135,-133,-132,-129,-131,-568,-533,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
1,166,55764,chair,-133,-139,-141,-141,-143,-495,-486,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
2,166,55764,chair,-142,-143,-138,-142,-142,96,63,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137
3,165,55762,chair,-210,-208,-208,-208,-200,-204,-357,...,-203,-204,-203,-207,-208,-209,-210,-213,-211,-214
4,165,55762,chair,-171,-166,-167,-168,-165,-407,-453,...,-162,-171,-175,-175,-173,-170,-173,-172,-171,-176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,32,55596,person,-117,-120,-112,-113,-114,-114,-169,...,-115,-114,-114,-114,-115,-123,-119,-115,-119,-116
639,31,55594,person,-162,-164,-160,-153,-151,-147,-456,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
640,31,55594,person,-153,-153,-154,-150,-150,-153,-168,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
641,31,55594,person,-158,-158,-159,-158,-156,-404,-454,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
642,31,55594,person,-149,-150,-148,-146,-148,-144,-219,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148

In [115]:
df_test6_prediction.drop(["total_count"], axis=1, inplace=True)

In [116]:
df_test6_prediction

     timestamp prediction
0        55780      chair
1        55780      chair
2        55778      chair
3        55776      chair
4        55775      chair
..         ...        ...
172      55572     person
173      55571     person
174      55571     person
175      55570     person
176      55569     person

[177 rows x 2 columns]

In [117]:
df_experimental_data

,timestamp,19,20,21,22,23,24,25,26,27,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,55593,-167,-168,-169,-169,-169,-161,41,73,94,...,-146,-150,-154,-150,-155,-159,-166,-167,-169,-162
1,55594,-162,-164,-160,-153,-151,-147,-456,-502,-542,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
2,55594,-153,-153,-154,-150,-150,-153,-168,-169,-169,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
3,55594,-158,-158,-159,-158,-156,-404,-454,-494,-539,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
4,55594,-149,-150,-148,-146,-148,-144,-219,-280,-346,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,55763,-162,-169,-162,-162,-161,-161,-87,-154,-218,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
796,55763,-162,-169,-162,-162,-161,-161,-87,-154,-218,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
797,55764,-135,-133,-132,-129,-131,-568,-533,-491,-436,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
798,55764,-133,-139,-141,-141,-143,-495,-486,-461,-422,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
799,55764,-142,-143,-138,-142,-142,96,63,22,-26,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137

In [119]:
df_merged = df_test6_prediction.merge(df_experimental_data, how='inner')

In [120]:
df_merged

,timestamp,prediction,19,20,21,22,23,24,25,26,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,55764,chair,-135,-133,-132,-129,-131,-568,-533,-491,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
1,55764,chair,-133,-139,-141,-141,-143,-495,-486,-461,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
2,55764,chair,-142,-143,-138,-142,-142,96,63,22,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137
3,55762,chair,-210,-208,-208,-208,-200,-204,-357,-415,...,-203,-204,-203,-207,-208,-209,-210,-213,-211,-214
4,55762,chair,-171,-166,-167,-168,-165,-407,-453,-495,...,-162,-171,-175,-175,-173,-170,-173,-172,-171,-176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,55596,person,-117,-120,-112,-113,-114,-114,-169,-152,...,-115,-114,-114,-114,-115,-123,-119,-115,-119,-116
639,55594,person,-162,-164,-160,-153,-151,-147,-456,-502,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
640,55594,person,-153,-153,-154,-150,-150,-153,-168,-169,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
641,55594,person,-158,-158,-159,-158,-156,-404,-454,-494,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
642,55594,person,-149,-150,-148,-146,-148,-144,-219,-280,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148

import numpy as np

np.select(df_merged["prediction"] == "chair", choicelist=)

### selection chair rows

In [125]:
df_chair = df_merged.loc[df_merged['prediction'] == 'chair']
df_chair

,timestamp,prediction,19,20,21,22,23,24,25,26,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,55764,chair,-135,-133,-132,-129,-131,-568,-533,-491,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
1,55764,chair,-133,-139,-141,-141,-143,-495,-486,-461,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
2,55764,chair,-142,-143,-138,-142,-142,96,63,22,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137
3,55762,chair,-210,-208,-208,-208,-200,-204,-357,-415,...,-203,-204,-203,-207,-208,-209,-210,-213,-211,-214
4,55762,chair,-171,-166,-167,-168,-165,-407,-453,-495,...,-162,-171,-175,-175,-173,-170,-173,-172,-171,-176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,55680,chair,-152,-156,-160,-166,-168,-370,-309,-249,...,-146,-148,-151,-156,-161,-158,-163,-157,-153,-152
400,55679,chair,-184,-180,-180,-175,-164,-154,-157,-152,...,-187,-190,-191,-190,-193,-196,-194,-197,-194,-186
401,55679,chair,-60,-64,-77,-102,-118,-463,-444,-406,...,-65,-54,-42,-36,-29,-30,-40,-43,-48,-53
402,55679,chair,-165,-174,-177,-179,-179,-181,-125,-128,...,-111,-117,-120,-125,-130,-133,-142,-151,-152,-155
403,55679,chair,-165,-174,-177,-179,-179,-181,-125,-128,...,-111,-117,-120,-125,-130,-133,-142,-151,-152,-155

### selecting person rows

In [126]:
df_person = df_merged.loc[df_merged['prediction'] == 'person']
df_person

,timestamp,prediction,19,20,21,22,23,24,25,26,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
404,55677,person,-89,-91,-91,-88,-84,-47,-96,-158,...,-83,-85,-86,-88,-89,-91,-94,-94,-92,-89
405,55677,person,-166,-178,-182,-182,-183,110,96,74,...,-139,-144,-149,-159,-160,-169,-167,-166,-172,-172
406,55677,person,-157,-160,-165,-168,-168,-166,-56,-12,...,-129,-134,-129,-130,-137,-143,-144,-144,-149,-151
407,55677,person,-174,-174,-176,-184,-181,-176,110,118,...,-143,-148,-150,-151,-155,-159,-163,-166,-167,-172
408,55676,person,-144,-143,-146,-150,-153,-158,-155,-152,...,-149,-154,-154,-153,-152,-151,-152,-154,-150,-146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,55596,person,-117,-120,-112,-113,-114,-114,-169,-152,...,-115,-114,-114,-114,-115,-123,-119,-115,-119,-116
639,55594,person,-162,-164,-160,-153,-151,-147,-456,-502,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
640,55594,person,-153,-153,-154,-150,-150,-153,-168,-169,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
641,55594,person,-158,-158,-159,-158,-156,-404,-454,-494,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
642,55594,person,-149,-150,-148,-146,-148,-144,-219,-280,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148

### selecting others rows

In [124]:
df_merged.loc[df_merged['prediction'] == 'others']

Empty DataFrame
Columns: [timestamp, prediction, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, ...]
Index: []

[0 rows x 16386 columns]

In [128]:
df_chair.to_json("labeled_data/chair.json", orient='records')

In [129]:
df_person.to_json("labeled_data/person.json", orient='records')

In [130]:
df_test = df_person.copy()

In [131]:
df_test

,timestamp,prediction,19,20,21,22,23,24,25,26,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
404,55677,person,-89,-91,-91,-88,-84,-47,-96,-158,...,-83,-85,-86,-88,-89,-91,-94,-94,-92,-89
405,55677,person,-166,-178,-182,-182,-183,110,96,74,...,-139,-144,-149,-159,-160,-169,-167,-166,-172,-172
406,55677,person,-157,-160,-165,-168,-168,-166,-56,-12,...,-129,-134,-129,-130,-137,-143,-144,-144,-149,-151
407,55677,person,-174,-174,-176,-184,-181,-176,110,118,...,-143,-148,-150,-151,-155,-159,-163,-166,-167,-172
408,55676,person,-144,-143,-146,-150,-153,-158,-155,-152,...,-149,-154,-154,-153,-152,-151,-152,-154,-150,-146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,55596,person,-117,-120,-112,-113,-114,-114,-169,-152,...,-115,-114,-114,-114,-115,-123,-119,-115,-119,-116
639,55594,person,-162,-164,-160,-153,-151,-147,-456,-502,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
640,55594,person,-153,-153,-154,-150,-150,-153,-168,-169,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
641,55594,person,-158,-158,-159,-158,-156,-404,-454,-494,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
642,55594,person,-149,-150,-148,-146,-148,-144,-219,-280,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148

In [142]:
df_test.iloc[:, 2:].values

array([[ -89,  -91,  -91, ...,  -94,  -92,  -89],
       [-166, -178, -182, ..., -166, -172, -172],
       [-157, -160, -165, ..., -144, -149, -151],
       ...,
       [-153, -153, -154, ..., -143, -149, -152],
       [-158, -158, -159, ..., -159, -157, -156],
       [-149, -150, -148, ..., -144, -150, -148]], dtype=int64)

In [143]:
df_test.iloc[:, 2:].values.shape

(239, 16384)

In [144]:
test_data = df_test.iloc[:, 2:].values

In [145]:
test_data

array([[ -89,  -91,  -91, ...,  -94,  -92,  -89],
       [-166, -178, -182, ..., -166, -172, -172],
       [-157, -160, -165, ..., -144, -149, -151],
       ...,
       [-153, -153, -154, ..., -143, -149, -152],
       [-158, -158, -159, ..., -159, -157, -156],
       [-149, -150, -148, ..., -144, -150, -148]], dtype=int64)

In [146]:
pd.DataFrame(test_data)

,0,1,2,3,4,5,6,7,8,9,...,16374,16375,16376,16377,16378,16379,16380,16381,16382,16383
0,-89,-91,-91,-88,-84,-47,-96,-158,-228,-292,...,-83,-85,-86,-88,-89,-91,-94,-94,-92,-89
1,-166,-178,-182,-182,-183,110,96,74,47,11,...,-139,-144,-149,-159,-160,-169,-167,-166,-172,-172
2,-157,-160,-165,-168,-168,-166,-56,-12,33,65,...,-129,-134,-129,-130,-137,-143,-144,-144,-149,-151
3,-174,-174,-176,-184,-181,-176,110,118,113,96,...,-143,-148,-150,-151,-155,-159,-163,-166,-167,-172
4,-144,-143,-146,-150,-153,-158,-155,-152,-156,-157,...,-149,-154,-154,-153,-152,-151,-152,-154,-150,-146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,-117,-120,-112,-113,-114,-114,-169,-152,-134,-115,...,-115,-114,-114,-114,-115,-123,-119,-115,-119,-116
235,-162,-164,-160,-153,-151,-147,-456,-502,-542,-568,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
236,-153,-153,-154,-150,-150,-153,-168,-169,-169,-170,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
237,-158,-158,-159,-158,-156,-404,-454,-494,-539,-571,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
238,-149,-150,-148,-146,-148,-144,-219,-280,-346,-409,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148

In [147]:
td = test_data.reshape(239,1, 16384)

In [152]:
list_data = test_data.tolist()

In [154]:
series = pd.Series(list_data)

In [164]:
series

0      [-89, -91, -91, -88, -84, -47, -96, -158, -228...
1      [-166, -178, -182, -182, -183, 110, 96, 74, 47...
2      [-157, -160, -165, -168, -168, -166, -56, -12,...
3      [-174, -174, -176, -184, -181, -176, 110, 118,...
4      [-144, -143, -146, -150, -153, -158, -155, -15...
                             ...
234    [-117, -120, -112, -113, -114, -114, -169, -15...
235    [-162, -164, -160, -153, -151, -147, -456, -50...
236    [-153, -153, -154, -150, -150, -153, -168, -16...
237    [-158, -158, -159, -158, -156, -404, -454, -49...
238    [-149, -150, -148, -146, -148, -144, -219, -28...
Length: 239, dtype: object

In [165]:
series.shape

(239,)

In [158]:
df_test["data"] = series

In [159]:
df_test

,timestamp,prediction,19,20,21,22,23,24,25,26,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,data
404,55677,person,-89,-91,-91,-88,-84,-47,-96,-158,...,-85,-86,-88,-89,-91,-94,-94,-92,-89,NaN
405,55677,person,-166,-178,-182,-182,-183,110,96,74,...,-144,-149,-159,-160,-169,-167,-166,-172,-172,NaN
406,55677,person,-157,-160,-165,-168,-168,-166,-56,-12,...,-134,-129,-130,-137,-143,-144,-144,-149,-151,NaN
407,55677,person,-174,-174,-176,-184,-181,-176,110,118,...,-148,-150,-151,-155,-159,-163,-166,-167,-172,NaN
408,55676,person,-144,-143,-146,-150,-153,-158,-155,-152,...,-154,-154,-153,-152,-151,-152,-154,-150,-146,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,55596,person,-117,-120,-112,-113,-114,-114,-169,-152,...,-114,-114,-114,-115,-123,-119,-115,-119,-116,NaN
639,55594,person,-162,-164,-160,-153,-151,-147,-456,-502,...,-179,-177,-178,-176,-173,-172,-168,-166,-167,NaN
640,55594,person,-153,-153,-154,-150,-150,-153,-168,-169,...,-144,-145,-146,-144,-146,-141,-143,-149,-152,NaN
641,55594,person,-158,-158,-159,-158,-156,-404,-454,-494,...,-157,-159,-163,-162,-163,-159,-159,-157,-156,NaN
642,55594,person,-149,-150,-148,-146,-148,-144,-219,-280,...,-149,-144,-147,-148,-154,-149,-144,-150,-148,NaN

In [161]:
final_df = df_test.loc[:, ["timestamp", "prediction", "data"]]

In [163]:
final_df["data"]

404    NaN
405    NaN
406    NaN
407    NaN
408    NaN
      ...
638    NaN
639    NaN
640    NaN
641    NaN
642    NaN
Name: data, Length: 239, dtype: object

In [166]:
final_df["dataa"] = pd.DataFrame(series)

In [175]:
final_df["datttaa"] = series.values

In [177]:
final_df.dropna()

Empty DataFrame
Columns: [timestamp, prediction, data, dataa, datttaa]
Index: []

In [178]:
final_df

,timestamp,prediction,data,dataa,datttaa
404,55677,person,NaN,NaN,"[-89, -91, -91, -88, -84, -47, -96, -158, -228..."
405,55677,person,NaN,NaN,"[-166, -178, -182, -182, -183, 110, 96, 74, 47..."
406,55677,person,NaN,NaN,"[-157, -160, -165, -168, -168, -166, -56, -12,..."
407,55677,person,NaN,NaN,"[-174, -174, -176, -184, -181, -176, 110, 118,..."
408,55676,person,NaN,NaN,"[-144, -143, -146, -150, -153, -158, -155, -15..."
...,...,...,...,...,...
638,55596,person,NaN,NaN,"[-117, -120, -112, -113, -114, -114, -169, -15..."
639,55594,person,NaN,NaN,"[-162, -164, -160, -153, -151, -147, -456, -50..."
640,55594,person,NaN,NaN,"[-153, -153, -154, -150, -150, -153, -168, -16..."
641,55594,person,NaN,NaN,"[-158, -158, -159, -158, -156, -404, -454, -49..."
642,55594,person,NaN,NaN,"[-149, -150, -148, -146, -148, -144, -219, -28..."

In [181]:
final_df.dropna(axis=1, inplace=True)

In [184]:
final_df.rename(columns={"datttaa": "data"}, inplace=True)

In [185]:
final_df

     timestamp prediction                                               data
404      55677     person  [-89, -91, -91, -88, -84, -47, -96, -158, -228...
405      55677     person  [-166, -178, -182, -182, -183, 110, 96, 74, 47...
406      55677     person  [-157, -160, -165, -168, -168, -166, -56, -12,...
407      55677     person  [-174, -174, -176, -184, -181, -176, 110, 118,...
408      55676     person  [-144, -143, -146, -150, -153, -158, -155, -15...
..         ...        ...                                                ...
638      55596     person  [-117, -120, -112, -113, -114, -114, -169, -15...
639      55594     person  [-162, -164, -160, -153, -151, -147, -456, -50...
640      55594     person  [-153, -153, -154, -150, -150, -153, -168, -16...
641      55594     person  [-158, -158, -159, -158, -156, -404, -454, -49...
642      55594     person  [-149, -150, -148, -146, -148, -144, -219, -28...

[239 rows x 3 columns]

In [187]:
final_df.to_json("labeled_data/person_3cols.json", orient="records")

In [192]:
df_person.iloc[0, 16350:]

16367    -69
16368    -65
16369    -59
16370    -58
16371    -56
16372    -59
16373    -61
16374    -54
16375    -55
16376    -57
16377    -42
16378    -44
16379    -43
16380    -44
16381    -48
16382    -48
16383    -52
16384    -56
16385    -58
16386    -60
16387    -65
16388    -62
16389    -63
16390    -66
16391    -73
16392    -76
16393    -83
16394    -85
16395    -86
16396    -88
16397    -89
16398    -91
16399    -94
16400    -94
16401    -92
16402    -89
Name: 404, dtype: object